### ISSUE TITLE
Evaluate how to handle AP mode before Wi-Fi country is selected

### ISSUE THREAD

**Issue by m-roberts** [pi-top/Wi-Fi-Access-Point-and-Station-Mode#9]
Wi-Fi is blocked by default on a new image, but this will prevent us from being able to start AP mode. It may be that there is nothing we can do here, and the solution is to be handled in the user onboarding. e.g. use miniscreen to select Wi-Fi country so that AP mode can turn on.

**Comment by jcapona** [comment]
The wi-fi country is not actually necessary since AP-mode doesn't use `wpa_supplicant`, however the wireless card is disabled by default on first boot:

```
$ sudo wifi-ap-sta start
Creating virtual interface wlan_ap0 to run AP mode
Interface wlan_ap0 not ready - sleeping for 2 seconds...
Configuring hostapd ...
Setting static IP configuration in /etc/dhcpcd.conf ...
Setting subnet configuration in /etc/dhcp/dhcpd.conf ...
Configuring wlan_ap0 in /etc/default/isc-dhcp-server...
Starting Wifi: Access Point Mode ...
SIOCSIFFLAGS: Operation not possible due to RF-kill
```

```
$ rfkill list all
0: phy0: Wireless LAN
	Soft blocked: yes
	Hard blocked: no
1: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
```

This means that we need to check if the wireless card is enabled before starting AP mode, and enable it if necessary.
